export {};
type Scheme="http"|"https"|"socks4"|"socks5";
type Language="zh"|"en";
type Theme="light"|"dark";
interface Profile{id:string;name:string;scheme:Scheme;host:string;port:number;tags?:string[]}
interface Store{profiles?:Profile[];activeProfileId?:string|null;userAgent?:string|null;language?:Language;theme?:Theme;collapsedProfileIds?:string[]}
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector(s) as T;
const browserMajor=navigator.userAgent.match(/(?:Chrome|Chromium)\/(\d+)/)?.[1]||"140";
const UA_PRESETS=[
  {id:"chromeWindows",value:`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${browserMajor}.0.0.0 Safari/537.36`},
  {id:"edgeWindows",value:`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${browserMajor}.0.0.0 Safari/537.36 Edg/${browserMajor}.0.0.0`},
  {id:"chromeMac",value:`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${browserMajor}.0.0.0 Safari/537.36`},
  {id:"chromeAndroid",value:`Mozilla/5.0 (Linux; Android 15; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${browserMajor}.0.0.0 Mobile Safari/537.36`},
  {id:"safariIphone",value:"Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1"}
] as const;
const TEXT={
  zh:{direct:"直连",profiles:"代理节点",import:"导入 JSON",profileName:"节点名称",add:"添加",rotateUa:"换一个 UA",applyUa:"应用 User-Agent",uaPlaceholder:"留空以恢复浏览器默认 UA",empty:"导入 PortPilot JSON 文件<br>或添加第一个本地代理节点。",test:"测试",delete:"删除",expand:"展开节点信息",collapse:"折叠节点信息",checking:"检测中…",failed:"失败",unknown:"未知",imported:"已导入 {count} 个节点",importFailed:"导入失败",uaEnabled:"User-Agent 已启用",uaRestored:"已恢复浏览器默认 User-Agent",uaRotated:"已自动更换为 {name}",directStatus:"直连",proxyStatus:"代理已启用",hint:"Chrome 不支持需要账号密码认证的 SOCKS5。",defaultUa:"自定义 / 浏览器默认",chromeWindows:"Chrome / Windows",edgeWindows:"Edge / Windows",chromeMac:"Chrome / macOS",chromeAndroid:"Chrome / Android",safariIphone:"Safari / iPhone"},
  en:{direct:"Direct",profiles:"Proxy nodes",import:"Import JSON",profileName:"Node name",add:"Add",rotateUa:"Change UA",applyUa:"Apply User-Agent",uaPlaceholder:"Leave empty to restore the browser default UA",empty:"Import a PortPilot JSON file<br>or add your first local proxy.",test:"Test",delete:"Delete",expand:"Expand node details",collapse:"Collapse node details",checking:"Checking…",failed:"Failed",unknown:"Unknown",imported:"Imported {count} nodes",importFailed:"Import failed",uaEnabled:"User-Agent enabled",uaRestored:"Browser default User-Agent restored",uaRotated:"Changed automatically to {name}",directStatus:"Direct",proxyStatus:"Proxy active",hint:"Chrome does not support authenticated SOCKS5 proxies.",defaultUa:"Custom / browser default",chromeWindows:"Chrome / Windows",edgeWindows:"Edge / Windows",chromeMac:"Chrome / macOS",chromeAndroid:"Chrome / Android",safariIphone:"Safari / iPhone"}
} as const;
let state:{profiles:Profile[];activeProfileId:string|null;userAgent:string|null;language:Language;theme:Theme;collapsed:Set<string>}={profiles:[],activeProfileId:null,userAgent:null,language:"zh",theme:"light",collapsed:new Set()};
const t=(key:keyof typeof TEXT.zh,vars:Record<string,string|number>={})=>Object.entries(vars).reduce((value,[name,replacement])=>value.replace(`{${name}}`,String(replacement)),TEXT[state.language][key] as string);
function esc(value:string){const div=document.createElement("div");div.textContent=value;return div.innerHTML}
async function persistProfiles(){await chrome.storage.local.set({profiles:state.profiles})}
async function persistPreferences(){await chrome.storage.local.set({language:state.language,theme:state.theme,collapsedProfileIds:[...state.collapsed]})}
async function activate(profile:Profile|null){const result=await chrome.runtime.sendMessage({type:"SET_PROXY",profile});if(!result?.ok)throw new Error(result?.error||"Proxy update failed");state.activeProfileId=profile?.id??null;renderProfiles()}
function renderPresets(){const select=$<HTMLSelectElement>("#uaPreset");const current=UA_PRESETS.find(item=>item.value===$<HTMLTextAreaElement>("#ua").value);select.innerHTML=`<option value="">${t("defaultUa")}</option>${UA_PRESETS.map(item=>`<option value="${item.id}">${t(item.id)}</option>`).join("")}`;select.value=current?.id||""}
function renderProfiles(){const list=$("#profiles");list.innerHTML=state.profiles.length?state.profiles.map(profile=>{const collapsed=state.collapsed.has(profile.id);return `<article class="profile ${profile.id===state.activeProfileId?"active":""} ${collapsed?"collapsed":""}" data-id="${esc(profile.id)}"><div class="profile-row"><button class="toggle" data-action="toggle" aria-label="${t(collapsed?"expand":"collapse")}" title="${t(collapsed?"expand":"collapse")}">⌄</button><div class="profile-name"><strong>${esc(profile.name)}</strong></div><button class="action" data-action="test">${t("test")}</button><button class="action" data-action="delete" aria-label="${t("delete")}" title="${t("delete")}">×</button></div><div class="profile-detail"><span>${profile.scheme.toUpperCase()} · ${esc(profile.host)}:${profile.port}</span>${profile.tags?.length?`<br><span>${profile.tags.map(esc).join(" · ")}</span>`:""}</div></article>`}).join(""):`<div class="empty">${t("empty")}</div>`;$("#status").textContent=t(state.activeProfileId?"proxyStatus":"directStatus").toUpperCase();$("#direct").classList.toggle("active",!state.activeProfileId)}
function renderLanguage(){document.documentElement.lang=state.language==="zh"?"zh-CN":"en";document.querySelectorAll<HTMLElement>("[data-i18n]").forEach(el=>{el.textContent=t(el.dataset.i18n as keyof typeof TEXT.zh)});document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>("[data-i18n-placeholder]").forEach(el=>{el.placeholder=t(el.dataset.i18nPlaceholder as keyof typeof TEXT.zh)});$("#language").textContent=state.language==="zh"?"EN":"中文";renderPresets();renderProfiles();if(!$("#checkResult").dataset.message)$("#checkResult").textContent=t("hint")}
function renderTheme(){document.documentElement.dataset.theme=state.theme;$("#theme").textContent=state.theme==="light"?"☾":"☀"}
function showMessage(key:keyof typeof TEXT.zh,vars:Record<string,string|number>={}){const output=$("#checkResult");output.dataset.message=key;output.textContent=t(key,vars)}
async function check(profile:Profile){showMessage("checking");const old=state.profiles.find(p=>p.id===state.activeProfileId)||null;const started=performance.now();try{await activate(profile);const controller=new AbortController();setTimeout(()=>controller.abort(),10000);const response=await fetch("https://ipwho.is/",{cache:"no-store",signal:controller.signal});const data=await response.json();if(!response.ok||data.success===false)throw new Error(data.message||`HTTP ${response.status}`);$("#checkResult").textContent=`${data.ip} / ${data.country||t("unknown")} / ${Math.round(performance.now()-started)} ms`}catch(error){await activate(old);$("#checkResult").textContent=`${t("failed")} / ${error instanceof Error?error.message:String(error)}`}}
async function applyUa(value:string|null,message?:()=>void){const result=await chrome.runtime.sendMessage({type:"SET_UA",value});if(!result?.ok)throw new Error(result?.error||"User-Agent update failed");state.userAgent=value;$<HTMLTextAreaElement>("#ua").value=value||"";renderPresets();message?.()}
async function init(){const saved=await chrome.storage.local.get(["profiles","activeProfileId","userAgent","language","theme","collapsedProfileIds"]) as Store;state={profiles:saved.profiles||[],activeProfileId:saved.activeProfileId||null,userAgent:saved.userAgent||null,language:saved.language||"zh",theme:saved.theme||"light",collapsed:new Set(saved.collapsedProfileIds||[])};$<HTMLTextAreaElement>("#ua").value=state.userAgent||"";renderTheme();renderLanguage()}
$("#profiles").addEventListener("click",async event=>{const target=event.target as HTMLElement,button=target.closest<HTMLButtonElement>("button"),card=target.closest<HTMLElement>(".profile");if(!card)return;const profile=state.profiles.find(item=>item.id===card.dataset.id);if(!profile)return;if(button?.dataset.action==="toggle"){state.collapsed.has(profile.id)?state.collapsed.delete(profile.id):state.collapsed.add(profile.id);await persistPreferences();renderProfiles()}else if(button?.dataset.action==="delete"){state.profiles=state.profiles.filter(item=>item.id!==profile.id);state.collapsed.delete(profile.id);if(state.activeProfileId===profile.id)await activate(null);await Promise.all([persistProfiles(),persistPreferences()]);renderProfiles()}else if(button?.dataset.action==="test")await check(profile);else if(!button)await activate(profile)});
$("#direct").addEventListener("click",()=>void activate(null));
$("#language").addEventListener("click",async()=>{state.language=state.language==="zh"?"en":"zh";await persistPreferences();renderLanguage()});
$("#theme").addEventListener("click",async()=>{state.theme=state.theme==="light"?"dark":"light";await persistPreferences();renderTheme()});
$<HTMLInputElement>("#import").addEventListener("change",async event=>{const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.schemaVersion!==1||!Array.isArray(data.profiles))throw new Error("Unsupported file");const valid=data.profiles.every((p:Profile)=>p.id&&p.name&&["http","https","socks4","socks5"].includes(p.scheme)&&p.host&&Number.isInteger(p.port)&&p.port>0&&p.port<65536);if(!valid)throw new Error("Invalid profile");state.profiles=data.profiles;await persistProfiles();renderProfiles();showMessage("imported",{count:data.profiles.length})}catch(error){$("#checkResult").textContent=`${t("importFailed")} / ${error instanceof Error?error.message:String(error)}`}finally{input.value=""}});
$<HTMLFormElement>("#addForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.target as HTMLFormElement,data=new FormData(form),port=Number(data.get("port"));if(port<1||port>65535)return;state.profiles.push({id:`manual-${Date.now().toString(36)}`,name:String(data.get("name")),scheme:String(data.get("scheme")) as Scheme,host:String(data.get("host")),port});await persistProfiles();form.reset();renderProfiles()});
$<HTMLSelectElement>("#uaPreset").addEventListener("change",event=>{const preset=UA_PRESETS.find(item=>item.id===(event.target as HTMLSelectElement).value);$<HTMLTextAreaElement>("#ua").value=preset?.value||""});
$("#rotateUa").addEventListener("click",async()=>{const candidates=UA_PRESETS.filter(item=>item.value!==state.userAgent);const selected=candidates[Math.floor(Math.random()*candidates.length)]||UA_PRESETS[0];await applyUa(selected.value,()=>showMessage("uaRotated",{name:t(selected.id)}))});
$("#applyUa").addEventListener("click",async()=>{const value=$<HTMLTextAreaElement>("#ua").value.trim()||null;await applyUa(value,()=>showMessage(value?"uaEnabled":"uaRestored"))});
void init();
